export default `Begin
  \${first.alpha} => 32
  \${first.bravo} => 78
  \${first.charlie} => "Charlie"
  \${first.delta} => ()
  \${first.echo} => "echo"
  \${first.foxtrot} => False
  \${first.golf} => ()
  \${first.hotel} => ()
  \${first.india} => ()
  \${first.juliett} => ("a","b","c","d","e",)
  \${first.kilo} => (True,False,False,True,True,)
  \${first.mike} => "Bar"
  \${first.november} => 0
  \${first.oscar} => E1[A:8 - B:9]
  \${first.papa} => E1[A:12 - B:13]
  \${first.romeo.a} => 8
  \${first.romeo.b} => 9
  \${first.sierra.someNumber} => 567
  \${first.sierra.someString} => "alpha"
  \${first.sierra.someString2} => "beta"
  \${first.sierra.someBoolean} => True
  \${first.sierra.someBoolean2} => False
  \${first.sierra.someObjectString} => "gamma"
  \${first.sierra.someArray} => (400,500,600,700,800,)
  \${first.sierra.someEntity} => E1[A:8 - B:9]
  \${second(0).a} => 1
  \${second(0).b} => 2
  \${second(1)} => E1[A:11 - B:22]
End`
