import IInputPinTemplate from "./IInputPinTemplate"
import Utility from "../Utility"

/**
 * @typedef {import("../element/PinElement").default} PinElement
 */

export default class RealPinTemplate extends IInputPinTemplate {

    /**
     * @param {PinElement} pin
     * @param {String[]?} values
     */
    setInputs(pin, values = []) {
        let num = parseFloat(values.length ? values[0] : this.getInput(pin))
        let updateDefaultValue = true
        if (isNaN(num)) {
            num = parseFloat(pin.entity.DefaultValue != ""
                ? /** @type {String} */(pin.entity.DefaultValue)
                : pin.entity.AutogeneratedDefaultValue)
        }
        if (isNaN(num)) {
            num = 0
            updateDefaultValue = false
        }
        values[0] = Utility.minDecimals(num)
        super.setInputs(pin, values, updateDefaultValue)
    }
}
