import Entity from "./Entity"
import Guid from "./primitive/Guid"
import LocalizedTextEntity from "./LocalizedTextEntity"
import ObjectReference from "./primitive/ObjectReference"
import PinReferenceEntity from "./PinReferenceEntity"
import TypeInitialization from "./TypeInitialization"

export default class PinEntity extends Entity {

    static attributes = {
        PinId: Guid,
        PinName: "",
        PinFriendlyName: new TypeInitialization(LocalizedTextEntity, false, null),
        PinToolTip: "",
        Direction: new TypeInitialization(String, false, ""),
        PinType: {
            PinCategory: "",
            PinSubCategory: "",
            PinSubCategoryObject: ObjectReference,
            PinSubCategoryMemberReference: null,
            PinValueType: null,
            ContainerType: ObjectReference,
            bIsReference: false,
            bIsConst: false,
            bIsWeakPointer: false,
            bIsUObjectWrapper: false
        },
        LinkedTo: [PinReferenceEntity],
        DefaultValue: "",
        AutogeneratedDefaultValue: "",
        PersistentGuid: Guid,
        bHidden: false,
        bNotConnectable: false,
        bDefaultValueIsReadOnly: false,
        bDefaultValueIsIgnored: false,
        bAdvancedView: false,
        bOrphanedPin: false,
    }

    getAttributes() {
        return PinEntity.attributes
    }

    isOutput() {
        if (this.Direction === "EGPD_Output") {
            return true
        }
    }
}
